# Generated by Django 5.1.6 on 2026-03-26 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attorney",
            fields=[
                (
                    "registration_no",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "application_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.TextField(blank=True, null=True)),
                (
                    "applicant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "inventor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gau", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PatentAttorney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attorney",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.attorney"
                    ),
                ),
                (
                    "patent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attorneys_map",
                        to="core.patent",
                    ),
                ),
            ],
            options={
                "unique_together": {("patent", "attorney")},
            },
        ),
    ]
