# Generated by Django 5.1.6 on 2026-03-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gau", models.CharField(max_length=20)),
                ("total_cases", models.IntegerField(default=0)),
                ("approved", models.IntegerField(default=0)),
                ("rejected", models.IntegerField(default=0)),
                ("pending", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(default=0)),
                (
                    "attorney",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.attorney"
                    ),
                ),
            ],
            options={
                "unique_together": {("attorney", "gau")},
            },
        ),
    ]
